name: build all (Debug)

on:
  workflow_call:

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  debug-coverage:
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            coverage: ON
    uses: ./.github/workflows/build-test.yml
    with:
      compiler: ${{ matrix.compiler }}
      type: Debug
      name: "Debug: ${{ matrix.compiler }}, coverage ${{ matrix.coverage }}"
  
  sanitize-address:
    strategy:
      matrix:
        lib_msg_delivery: [ON, OFF]
        lib_write_deadline: [ON, OFF]
        exclude:
          - lib_msg_delivery: ON
            lib_write_deadline: ON
    uses: ./.github/workflows/build-test.yml
    with:
      sanitize: address
      lib_msg_delivery: ${{ matrix.lib_msg_delivery }}
      lib_write_deadline: ${{ matrix.lib_write_deadline }}
      name: "Sanitize address: ${{ (matrix.lib_msg_delivery == 'ON' && matrix.lib_write_deadline == 'OFF' && 'msg-delivery') || (matrix.lib_msg_delivery == 'OFF' && matrix.lib_write_deadline == 'ON' && 'write-deadline') || 'default' }}"
  
  sanitize-thread:
    uses: ./.github/workflows/build-test.yml
    with:
      sanitize: thread
      name: "Sanitize thread: default"
