name: debug
on:
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag ref to checkout'
        required: true
        default: ${{ github.event.inputs.ref || github.ref }}
        type: string

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  testcov:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: gcc
            coverage: ON
          - compiler: clang
            coverage: OFF
    uses: ./.github/workflows/build-test.yml
    with:
      name: "${{ matrix.compiler }}: coverage ${{ matrix.coverage }}"
      type: Debug
      ref: ${{ inputs.ref }}
      compiler: ${{ matrix.compiler }}
      coverage: ${{ matrix.coverage }}
    secrets:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  san-addr:
    strategy:
      fail-fast: false
      matrix:
        lib_msg_delivery: [ON, OFF]
        lib_write_deadline: [ON, OFF]
        exclude:
          - lib_msg_delivery: ON
            lib_write_deadline: ON
    uses: ./.github/workflows/build-test.yml
    with:
      name: "gcc: sanitize address: ${{ (matrix.lib_msg_delivery == 'ON' && matrix.lib_write_deadline == 'OFF' && 'msg-delivery') || (matrix.lib_msg_delivery == 'OFF' && matrix.lib_write_deadline == 'ON' && 'write-deadline') || 'default' }}"
      type: Debug
      ref: ${{ inputs.ref }}
      sanitize: address
      lib_msg_delivery: ${{ matrix.lib_msg_delivery }}
      lib_write_deadline: ${{ matrix.lib_write_deadline }}
    secrets:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  san-thread:
    uses: ./.github/workflows/build-test.yml
    with:
      ref: ${{ inputs.ref }}
      sanitize: thread
      name: "gcc: sanitize thread"
    secrets:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
