name: build all (Release)

on:
  workflow_call:

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        ubuntu_version: [latest, 20.04]
    uses: ./.github/workflows/build-test.yml
    with:
      ubuntu_version: ${{ matrix.ubuntu_version }}
      compiler: ${{ matrix.compiler }}
      name: "ubuntu-${{ matrix.ubuntu_version }} ${{ matrix.compiler }}: latest"

  more-server-versions:
    needs: default
    strategy:
      fail-fast: false
      matrix:
        server_version: [main, dev, v2.9.11]
    uses: ./.github/workflows/build-test.yml
    with:
      server_version: ${{ matrix.server_version }}
      name: "ubuntu-latest gcc: ${{ matrix.server_version }}"

  TLS-OFF:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    uses: ./.github/workflows/build-test.yml
    with:
      tls: OFF
      name: "ubuntu-latest ${{ matrix.compiler }}: no TLS, latest"

  older-cc:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-7, gcc-8, clang-8]
    uses: ./.github/workflows/build-test.yml
    with:
      ubuntu_version: 20.04
      compiler: ${{ matrix.compiler }}
      quick_test: ON
      name: "ubuntu-20.04 (${{ matrix.compiler }}: quick check"

  no-streaming:
    uses: ./.github/workflows/build-test.yml
    with:
      streaming: OFF
      name: "ubuntu-latest gcc: no streaming, latest"
