name: build and test
on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "64"
      compiler:
        type: string
        default: "gcc"
      name:
        type: string
        description: "name of the build"
        default: "build"
      quick_test:
        type: string
        default: "OFF"
      server_version:
        type: string
        description: "nats-server version to test with"
        default: "latest"
      streaming:
        type: string
        default: "ON"
      tls:
        type: string
        default: "ON"
      type:
        type: string
        description: "Debug or Release."
        default: "Release"

defaults:
  run:
    shell: powershell -NonInteractive 

jobs:
  build-test:
    runs-on: windows-latest
    name: ${{ inputs.name }}
    steps:
      - name: Checkout nats.c
        uses: actions/checkout@v3

      - name: "Checkout dependencies (nats.c.deps)"
        uses: actions/checkout@v3
        with:
          repository: nats-io/nats.c.deps
          path: deps

      # configure the cmake flags and NATS_... environment variables
      # - id: cmake-flags
      #   name: Configure cmake flags
        # env:
        #   flags: -DNATS_BUILD_ARCH=${{ inputs.arch }}
        #     -DCMAKE_BUILD_TYPE=${{ inputs.type }}
        #     -DNATS_BUILD_STREAMING=${{ inputs.streaming }}
        #     -DNATS_BUILD_WITH_TLS=${{ inputs.tls }}
        #     -DNATS_PROTOBUF_DIR="${GITHUB_WORKSPACE}\\deps\\pbuf"
        #     -DNATS_BUILD_USE_SODIUM=ON
        #     -DNATS_SODIUM_DIR="${GITHUB_WORKSPACE}\\deps\\sodium"
        # run: |
        #   export flags = "-DNATS_BUILD_ARCH=${{ inputs.arch }} \
        #     -DCMAKE_BUILD_TYPE=${{ inputs.type }} \
        #     -DNATS_BUILD_STREAMING=${{ inputs.streaming }} \
        #     -DNATS_BUILD_WITH_TLS=${{ inputs.tls }} \
        #     -DNATS_PROTOBUF_DIR=${GITHUB_WORKSPACE}\\deps\\pbuf \
        #     -DNATS_BUILD_USE_SODIUM=ON \
        #     -DNATS_SODIUM_DIR=${GITHUB_WORKSPACE}\\deps\\sodium"
        #   echo $flags
        #   echo "flags=$flags" >> $GITHUB_OUTPUT
        #   echo "CC=${{ inputs.compiler }}" >> $GITHUB_ENV

      # otherwise, configure cmake, build, archive and upload
      - name: CMake
        run: |
          mkdir -p build
          cd build
          export CC=${{ inputs.compiler }}
          export NATS_BUILD_ARCH=${{ inputs.arch }}
          export NATS_BUILD_STREAMING=${{ inputs.streaming }}
          export NATS_BUILD_WITH_TLS=${{ inputs.tls }}
          export NATS_PROTOBUF_DIR="${GITHUB_WORKSPACE}\\deps\\pbuf"
          export NATS_BUILD_USE_SODIUM=ON
          export NATS_SODIUM_DIR="${GITHUB_WORKSPACE}\\deps\\sodium"
          export CMAKE_BUILD_TYPE=${{ inputs.type }}
          cmake .. 
          make rebuild_cache && make