name: build all (Release)

on:
  workflow_call:

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}    

jobs:
  default:
    name: "Default (latest): ubuntu-${{ matrix.ubuntu_version }} ${{ matrix.compiler }}"
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        ubuntu_version: [latest, 20.04]
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
      - name: Checkout nats.c
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-test-ubuntu
        with:
          ubuntu_version: ${{ matrix.ubuntu_version }}
          compiler: ${{ matrix.compiler }}

  more-server-versionss:
    name: "With NATS ${{ matrix.server_version }}: ubuntu-latest gcc "
    needs: default
    strategy:
      fail-fast: false
      matrix:
        server_version: [main, dev, v2.9.11]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nats.c
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-test-ubuntu
        with:
          server_version: ${{ matrix.server_version }}

  TLS-OFF:
    name: "TLS OFF: ubuntu-latest ${{ matrix.compiler }}"
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nats.c
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-test-ubuntu
        with:
          tls: OFF

  older-cc:
    name: "Quick check: ubuntu-20.04 (${{ matrix.compiler }})"
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc-7, gcc-8, clang-8]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout nats.c
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-test-ubuntu
        with:
          ubuntu_version: 20.04
          compiler: ${{ matrix.compiler }}
          quick_test: ON

  no-streaming:
    name: "Streaming OFF: ubuntu-latest gcc"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nats.c
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-test-ubuntu
        with:
          streaming: OFF