name: main to test2 cherry-picker COMMENT

on:
  issue_comment:
    types: [created]
    # branches:
    #   - test1

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  cherry-pick:
    name: Cherry-pick COMMENT
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true && startsWith(github.event.comment.body, '/cherry-pick')
    steps:
      - name: run hack cherry-pick
        run: | 
          pwd
          export
          ./.github/hack/cherry-pick.sh testing123