name: New Release

on:
  workflow_dispatch:
    # inputs:
    # kind:
    #   type: choice
    #   required: true
    #   description: "Type of the release (major, minor, or patch)"
    #   options:
    #     - major
    #     - minor
    #     - patch
    # update_required_lib_version:
    #   type: boolean
    #   description: "Require the library version to match the release version"

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

permissions:
  contents: write
  pull-requests: write

jobs:
  make_branch:
    runs-on: ubuntu-latest

    outputs:
      pr: ${{ steps.version.outputs.release_pr_branch }}
      release: ${{ steps.version.outputs.release_branch }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: "Checkout dependencies (nats.c.deps)"
        uses: actions/checkout@v3
        with:
          repository: nats-io/nats.c.deps
          path: deps

      - name: Gather version information
        id: version
        run: |
          MAJOR=$(grep "set(NATS_VERSION_MAJOR" CMakeLists.txt | awk -F'[ )]' '{print $3}')
          MINOR=$(grep "set(NATS_VERSION_MINOR" CMakeLists.txt | awk -F'[ )]' '{print $3}')
          PATCH=$(grep "set(NATS_VERSION_PATCH" CMakeLists.txt | awk -F'[ )]' '{print $3}')
          RELEASE_BRANCH="release/v${MAJOR}.${MINOR}"
          RELEASE_PR_BRANCH="release-pr/v${MAJOR}.${MINOR}-${{github.sha}}"

          echo "major=$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "patch=$PATCH" >> $GITHUB_OUTPUT
          echo "release_branch=${RELEASE_BRANCH}" >> $GITHUB_OUTPUT
          echo "release_pr_branch=${RELEASE_PR_BRANCH}" >> $GITHUB_OUTPUT
          echo "version=v${MAJOR}.${MINOR}.${PATCH}" >> $GITHUB_OUTPUT

      - name: Make ${{steps.version.outputs.release_branch}} branch
        if: steps.version.outputs.patch == '0'
        run: |
          git checkout -b ${{steps.version.outputs.release_branch}}
          git push origin ${{steps.version.outputs.release_branch}}

      - name: Use existing ${{steps.version.outputs.release_branch}} branch
        if: steps.version.outputs.patch != '0'
        run: |
          if [[ "${{github.ref_name}}" != "${{steps.version.outputs.release_branch}}" ]]; then
            echo "ERROR: You are trying to cut a patch release ${{steps.version.outputs.version}} from branch ${{github.ref_name}}. A patch release must be cut from an existing release branch."
            exit 1
          fi

      - name: Configure local git
        run: |
          git config --global user.name 'cut-release for ${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git checkout -b ${{steps.version.outputs.release_pr_branch}}

      - name: Remove "beta" from version
        run: |
          sed -i -E 's/^set\(NATS_VERSION_SUFFIX.*$/set(NATS_VERSION_SUFFIX "")/g' CMakeLists.txt
          grep "set(NATS_VERSION_" CMakeLists.txt

      - name: Update NATS_VERSION_REQUIRED_NUMBER if not a patch release
        # <>/<> TODO add a triggering input
        if: steps.version.outputs.patch == '0'
        run: |
          major_hex=$(printf "%02x" ${{steps.version.outputs.major}})
          echo ${major_hex}
          minor_hex=$(printf "%02x" ${{steps.version.outputs.minor}})
          echo ${minor_hex}
          regexp='^set\(NATS_VERSION_REQUIRED_NUMBER.*$'
          sed -i -E "s/$regexp/set(NATS_VERSION_REQUIRED_NUMBER 0x${major_hex}${minor_hex}00)/g" CMakeLists.txt
          grep "set(NATS_VERSION_" CMakeLists.txt

      - name: Rebuild with updated version
        run: |
          mkdir -p build
          cd build
          cmake .. -DNATS_PROTOBUF_DIR=${{ github.workspace }}/deps/pbuf -DNATS_UPDATE_DOC=ON -DNATS_UPDATE_VERSION=ON
          make
          cd ..
          rm -rf deps
          git status
          git commit -a -m "Updated version to ${{steps.version.outputs.version}}"

      - name: Generate the docs
        run: |
          sudo apt-get -q update
          sudo apt-get -y install doxygen
          cd doc
          doxygen DoxyFile.NATS.Client
          git add html
          git status
          git commit -a -m "Updated docs for ${{steps.version.outputs.version}}"

      - name: Push the changes
        id: branch
        run: |
          git push origin ${{steps.version.outputs.release_pr_branch}}

  # build-release:
  #   needs: make_branch
  #   uses: ./.github/workflows/build-release.yml
  #   with:
  #     ref: ${{ needs.make_branch.outputs.pr }}

  create_pr:
    needs: [make_branch] # , build-release]
    runs-on: ubuntu-latest

    steps:
      - name: Create the release PR with gh
        id: pr
        # env:
          # GITHUB_TOKEN: ${{secrets.CUT_RELEASE_TOKEN}}
        run: |
          PR_URL=$(gh pr create \
            --title "Release ${{needs.make_branch.outputs.version}}" \
            --body "This PR was automatically generated by cut-release. When it is merged, it will publish the release to GitHub, etc." \
            --base ${{needs.make_branch.outputs.release}} \
            --head ${{needs.make_branch.outputs.pr}} \
            --milestone ${{needs.make_branch.outputs.version}} \
            --label release)
          # echo "ref=$(gh pr view $PR_URL --json headRefOid | jq -r '.headRefOid') " >> $GITHUB_OUTPUT
          echo "ref=pull/$(gh pr view $PR_URL --json number | jq -r '.number')/merge" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.pr.outputs.ref }}
