name: Merge `main` to `dev`
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  backport:
    name: Backport on PR merge
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged
      && github.event.action == 'closed'
      && contains(github.event.pull_request.labels.*.name, 'backport-to-dev')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge
        run: | 
          ./.github/hack/merge-branch.sh test2 ${{github.event.pull_request.number}} ${{github.event.pull_request.merge_commit_sha}}
