name: "Release"
on:
  push:

permissions:
  contents: write # required by build-test to comment on coverage but not used here.

defaults:
  run:
    shell: bash --noprofile --norc -x -eo pipefail {0}

jobs:
  quick:
    name: "Ubuntu"
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        ubuntu_version: [latest, 20.04]
    uses: ./.github/workflows/build-test.yml
    with:
      server_version: main
      ubuntu_version: ${{ matrix.ubuntu_version }}
      compiler: ${{ matrix.compiler }}

  dev-mode:
    name: "DEV_MODE"
    uses: ./.github/workflows/build-test.yml
    with:
      dev_mode: ON
      server_version: main
      verbose_test_output: ON
      verbose_make_output: ON

  sanitize-addr:
    name: "Sanitize address"
    uses: ./.github/workflows/build-test.yml
    with:
      sanitize: address
      server_version: main

  san-thread:
    name: "Sanitize thread"
    uses: ./.github/workflows/build-test.yml
    with:
      sanitize: thread
      server_version: main
