# name: updated
# on:
#   pull_request:
#     types:
#       - synchronize
#       - opened

# permissions:
#   contents: write # so it can comment

# jobs:
#   build-debug:
#     uses: ./.github/workflows/build-all-debug.yml
#     secrets:
#       COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#   build-release:
#     if: |
#       contains(github.event.pull_request.labels.*.name, 'build-release')
#     uses: ./.github/workflows/build-all-release.yml
