on: [push]

jobs:
  build-debug:
    uses: ./.github/workflows/build-all-debug.yml

  build-release:
    if: |
      github.ref == 'refs/heads/test-gh-actions' || 
      github.ref == 'refs/heads/main' || 
      startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/build-all-release.yml
