name: "Debug"
on:
  pull_request:

permissions:
  contents: write # so it can comment

jobs:
  Ubuntu:
    name: "Ubuntu"
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    uses: ./.github/workflows/build-test.yml
    with:
      compiler: ${{ matrix.compiler }}
      server_version: main
      type: Debug

  coverage:
    name: "Coverage"
    uses: ./.github/workflows/build-test.yml
    with:
      coverage: ON
      server_version: main
      type: Debug
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  coverage-pooled:
    name: "Coverage"
    uses: ./.github/workflows/build-test.yml
    with:
      coverage: ON
      server_version: main
      type: Debug
      lib_msg_delivery: ON
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  dev-mode:
    name: "DEV_MODE"
    uses: ./.github/workflows/build-test.yml
    with:
      dev_mode: ON
      server_version: main
      type: Debug
      verbose_test_output: ON
      verbose_make_output: ON

  sanitize:
    name: "Sanitize"
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        sanitize: [address, thread]
        pooled_delivery: [ON, OFF]
    uses: ./.github/workflows/build-test.yml
    with:
      server_version: main
      type: Debug
      compiler: ${{ matrix.compiler }}
      sanitize: ${{ matrix.sanitize }}
      lib_msg_delivery: ${{ matrix.pooled_delivery }}

  san-addr-deadline:
    name: "Sanitize address (lib_write_deadline)"
    uses: ./.github/workflows/build-test.yml
    with:
      type: Debug
      sanitize: address
      server_version: main
      lib_write_deadline: ON

  Windows:
    name: "Windows"
    runs-on: windows-latest
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout nats.c
        uses: actions/checkout@v4

      - name: Build
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          cmake -B build -S . -DCMAKE_C_FLAGS=/W4 -DNATS_BUILD_STREAMING=OFF
          cmake --build build --config Debug

      - name: Test
        run: |
          cd build
          ./bin/Debug/testsuite
