name: updated
on:
  pull_request_target:
    types:
      - synchronize
      - opened

permissions:
  contents: write # so it can comment

jobs:
  build-debug:
    uses: ./.github/workflows/build-all-debug.yml

  build-release:
    if: |
      contains(github.event.pull_request.labels.*.name, 'build-release')
    uses: ./.github/workflows/build-all-release.yml
