name: Pushed main, release
on:
  push:
    branches:
      - test-gh-actions
      - main
      - release/*

jobs:
  build-release:
    if: |
      github.ref == 'refs/heads/test-gh-actions' || 
      github.ref == 'refs/heads/main' || 
      startsWith(github.ref, 'refs/heads/release/')
    uses: ./.github/workflows/build-all-release.yml
